"use client";

import React, { useState } from "react";
import { SAMPLE_PRODUCTS } from "@/data/products";
import { NegotiationAgreement } from "@/types/negotiation";
import { AgreementCard } from "@/components/AgreementCard";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ArrowLeft, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";

export default function AgreementPage() {
  const router = useRouter();
  const sampleProduct = SAMPLE_PRODUCTS[0];

  // Placeholder sample agreement
  const [agreement, setAgreement] = useState<NegotiationAgreement>({
    id: "agree_aurora_9942",
    productId: sampleProduct.id,
    productName: sampleProduct.name,
    originalPrice: sampleProduct.originalPrice,
    finalAgreedPrice: 245.0,
    savingsAmount: sampleProduct.originalPrice - 245.0,
    selectedDelivery: sampleProduct.availableDeliveryOptions[1], // Express
    totalSettlementAmount: 245.0,
    currency: "USD",
    roundsCount: 3,
    createdAt: new Date().toISOString(),
    userApproved: false,
    termsSummary:
      "Buyer Agent agreed to final price of $245.00 USD with complimentary Express Air Delivery (2-day). Merchant waived $15.00 shipping fee. Transaction requires human approval before PayPal Sandbox charge.",
  });

  const [isApproving, setIsApproving] = useState(false);

  const handleApprove = () => {
    setIsApproving(true);
    setTimeout(() => {
      setAgreement((prev) => ({
        ...prev,
        userApproved: true,
        userApprovedAt: new Date().toISOString(),
      }));
      setIsApproving(false);
      router.push("/checkout");
    }, 600);
  };

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800 pb-6">
        <div>
          <Badge variant="success" className="mb-2">
            Step 2: Human Verification
          </Badge>
          <h1 className="text-3xl font-bold text-white tracking-tight">
            Transaction Agreement Review
          </h1>
          <p className="text-sm text-slate-400 mt-1">
            Review the negotiated terms generated by your Buyer Agent and Merchant Agent.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <Link href="/negotiate">
            <Button variant="outline" size="sm">
              <ArrowLeft className="w-4 h-4" />
              <span>Back to Negotiator</span>
            </Button>
          </Link>
        </div>
      </div>

      {/* Agreement Display */}
      <div className="max-w-3xl mx-auto">
        <AgreementCard
          agreement={agreement}
          onApprove={handleApprove}
          isApproved={agreement.userApproved}
          isLoading={isApproving}
        />
      </div>

      <div className="max-w-3xl mx-auto rounded-2xl bg-slate-900/60 border border-slate-800 p-6 space-y-3 text-xs text-slate-400">
        <div className="flex items-center gap-2 text-slate-200 font-semibold text-sm">
          <ShieldCheck className="w-4 h-4 text-blue-400" />
          <span>Payvia Zero-Trust Safeguard</span>
        </div>
        <p className="leading-relaxed">
          No funds are transferred automatically by autonomous agents. Settlement occurs strictly after explicit human authorization using PayPal Sandbox REST Orders v2.
        </p>
      </div>
    </div>
  );
}
